# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bauer < Formula
  desc "Automate BAU tasks with ease"
  homepage "https://github.com/muhammadbassiony/Bauer"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.3.1/Bauer_Darwin_x86_64.tar.gz"
      sha256 "179a16377a08a5c626b8bf33d8fb3151955de500346156bf977434a4dc9da736"

      def install
        bin.install "Bauer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.3.1/Bauer_Darwin_arm64.tar.gz"
      sha256 "f5d638641b4a19f558afb84c5aa15a1ee1e4633d2ccf3cda45a2250560a2fa9b"

      def install
        bin.install "Bauer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.3.1/Bauer_Linux_x86_64.tar.gz"
      sha256 "e5753d8905bc7f5d87ef1072035f3f3fd92a69a62f6ba5e80efdf1bad17f4f93"
      def install
        bin.install "Bauer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.3.1/Bauer_Linux_arm64.tar.gz"
      sha256 "7b764f1da7145e8bbc8606569ca8aa6e570ddd599993070baba642de452e9ff5"
      def install
        bin.install "Bauer"
      end
    end
  end
end
