# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bauer < Formula
  desc "Automate BAU tasks with ease"
  homepage "https://github.com/muhammadbassiony/Bauer"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.1.1/Bauer_Darwin_x86_64.tar.gz"
      sha256 "13d7870f585c898130af0150763d86d432d0809f2d0d9c94872571584d463210"

      def install
        bin.install "Bauer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.1.1/Bauer_Darwin_arm64.tar.gz"
      sha256 "1a4f39d8a837648b3b3524fa4b1decdf81539713249b7606b4ba6a92b0d11597"

      def install
        bin.install "Bauer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.1.1/Bauer_Linux_x86_64.tar.gz"
      sha256 "b6838cb8d940fb70b14ce627ef436614bb6e6e2fedef520b5e2c75413b2716b2"
      def install
        bin.install "Bauer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.1.1/Bauer_Linux_arm64.tar.gz"
      sha256 "75853170e96d344de73f72a4298e6737080207e4c7787c309024ce20feb64520"
      def install
        bin.install "Bauer"
      end
    end
  end
end
