# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bauer < Formula
  desc "Automate BAU tasks with ease"
  homepage "https://github.com/muhammadbassiony/Bauer"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.3.0/Bauer_Darwin_x86_64.tar.gz"
      sha256 "2e04f98a8718e42438ab663a82c190af22fcad8c99f62f2ba58d93ff34c08178"

      def install
        bin.install "Bauer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.3.0/Bauer_Darwin_arm64.tar.gz"
      sha256 "f3b6d5b885cc8c4119cb628465790a979ff00a8b6787b3ae1697156d02eb9e69"

      def install
        bin.install "Bauer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.3.0/Bauer_Linux_x86_64.tar.gz"
      sha256 "2c723501a58773c16b4df6b0105ca1c09aa0375ae44b267fb8891ae3219b2935"
      def install
        bin.install "Bauer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muhammadbassiony/Bauer/releases/download/v1.3.0/Bauer_Linux_arm64.tar.gz"
      sha256 "37daa130e60557df04e152c5ba14b2fc901f7b7102080549d758751bef3330c2"
      def install
        bin.install "Bauer"
      end
    end
  end
end
